import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



// import Explicacao from './Componentes/Explicacao';
// import Navegacao from './layout/Navegacao';
import Cabecalho from './layout/Cabecalho';
// import Footer from './layout/Footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       

      <div className={styles.div_Inicio}>
      <div className={styles.div_topo}>
        <Cabecalho />
        {/* <Navegacao /> */}
        <div className={styles.div_espaço}></div>
      </div>
      <div className={styles.main_div}>
        {/* <Explicacao /> */}
    
      </div>
      <div className={styles.div_footer}>
      {/* <Footer/> */}
      </div>
    </div>




      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
