import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



// import Explicacao from './Componentes/Explicacao';

import Cabecalho from './layout/Cabecalho';

import Corpo from './layout/Corpo';
import Rodape from './layout/Rodape';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sitio do Café</title>
        {/* <meta name="Sítio do café" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
        <meta  name="viewport"  content="minimum-scale=1, initial-scale=1, width=device-width"/>
      </Head>

 
        <Cabecalho />
        <Corpo/>
        {/* <div className={styles.div_espaço}></div> */}
    
      <div className={styles.main_div}>
        {/* <Explicacao /> */}
    
      </div>
      <div className={styles.div_footer}>
      <Rodape/>
      </div>
    {/* </div> */}
    </div>
  )
}
